/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 07-24-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class PSTA_ResetearEstatusContacto_sch_tst {
    @isTest
    static void test_execute(){
        Test.startTest();
        PSTA_ResetearEstatusContacto_sch sch = new PSTA_ResetearEstatusContacto_sch();
        sch.execute(null);
        Test.stopTest();
    }
}