/****************************************************************************************************
Desarrollado por: Unknown
Proyecto        : Actinver
Descripción     : Interfaz para las estructuras del body del request de los distintos callouts

Cambios (Versiones)
-----------------------------------------------------------------------------------------------------
No.     Fecha           Autor                   Descripción
-----   ----------      --------------------    -----------------------------------------------------
1.0     2024-08-14      Unknown			        Creación de la Clase.                                       
*/
public interface RequestBody_cls {  
    String serializeRequestBody( RequestBody_cls requestBody );
}